name: 'dbt_project_repo'
version: '1.0'
profile: 'Snowflake_Conn'

models:
  "dbt_project_repo":    # You can keep this for future use
    +materialized: table

  ".":                   # ⚠️ THIS is what enables root-level models
    +materialized: table
